/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Conexao.Basededados;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Libi Bizeque
 */
public class Consulta extends javax.swing.JFrame {

    /**
     * Creates new form Consulta
     */
    public Consulta() {
        initComponents();
             conexao = Basededados.conector();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel18 = new javax.swing.JLabel();
        argumento = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        idade = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        sexo = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nome1 = new javax.swing.JTextField();
        data = new javax.swing.JTextField();
        conctato = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        encarregado = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        endereco = new javax.swing.JTextPane();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(670, 500));
        getContentPane().setLayout(null);

        jLabel18.setText("Nome do aluno");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(70, 60, 71, 14);

        argumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                argumentoActionPerformed(evt);
            }
        });
        argumento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                argumentoKeyReleased(evt);
            }
        });
        getContentPane().add(argumento);
        argumento.setBounds(170, 50, 305, 30);

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel19.setText("Digite o nome do aluno que pretende consultar");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(157, 11, 365, 22);

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Título 5", "Título 6", "Título 7", "Título 8"
            }
        ));
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tabelaMouseEntered(evt);
            }
        });
        jScrollPane2.setViewportView(tabela);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 85, 620, 120);

        jLabel4.setText("ID");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 214, 11, 14);

        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        getContentPane().add(id);
        id.setBounds(134, 211, 66, 30);

        idade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idadeActionPerformed(evt);
            }
        });
        getContentPane().add(idade);
        idade.setBounds(134, 249, 119, 30);

        jLabel13.setText("Idade");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(10, 252, 28, 14);

        sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));
        sexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sexoActionPerformed(evt);
            }
        });
        getContentPane().add(sexo);
        sexo.setBounds(134, 277, 100, 30);

        jLabel12.setText("Data de cadastro");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(279, 252, 83, 14);

        jLabel5.setText("Nome do aluno");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(267, 214, 71, 14);

        nome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nome1ActionPerformed(evt);
            }
        });
        getContentPane().add(nome1);
        nome1.setBounds(356, 211, 196, 30);

        data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataActionPerformed(evt);
            }
        });
        getContentPane().add(data);
        data.setBounds(366, 249, 106, 30);

        conctato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conctatoActionPerformed(evt);
            }
        });
        getContentPane().add(conctato);
        conctato.setBounds(329, 303, 120, 30);

        jLabel16.setText("Contacto");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(267, 316, 44, 14);

        encarregado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encarregadoActionPerformed(evt);
            }
        });
        getContentPane().add(encarregado);
        encarregado.setBounds(134, 313, 115, 30);

        jLabel15.setText("Nome de encarregado");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(10, 316, 106, 14);

        jScrollPane3.setViewportView(endereco);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(133, 351, 315, 60);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton2.setText("Editar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton6.setText("Excluir");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Sair");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton7)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton6))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(467, 313, 164, 96);

        jLabel1.setText("Sexo");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 287, 24, 14);

        jLabel2.setText("Endereço");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 364, 45, 14);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Liby Bizequi\\Desktop\\image.jpg")); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 50, 640, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void sexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sexoActionPerformed

    private void nome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nome1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nome1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        editar();


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void encarregadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encarregadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_encarregadoActionPerformed

    private void idadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idadeActionPerformed

    private void conctatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conctatoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_conctatoActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
excluir();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void argumentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_argumentoKeyReleased

consulta();
        // TODO add your handling code here:
    }//GEN-LAST:event_argumentoKeyReleased

    private void tabelaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelaMouseEntered

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
preencher_Tabela();

        // TODO add your handling code here:
    }//GEN-LAST:event_tabelaMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
cancelar();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataActionPerformed

    private void argumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_argumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_argumentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField argumento;
    private javax.swing.JTextField conctato;
    private javax.swing.JTextField data;
    private javax.swing.JTextField encarregado;
    private javax.swing.JTextPane endereco;
    private javax.swing.JTextField id;
    private javax.swing.JTextField idade;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField nome1;
    private javax.swing.JComboBox<String> sexo;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    void editar(){
    String sql = "update estudantes set Nome_do_aluno=?,Idade=?,Data_de_cadastro=?,Sexo=?,Nome_de_encarregado=?,Conctato=?,Endereco=? where id=?";
        try {
            pst = conexao.prepareStatement(sql);
        
            pst.setString(1, nome1.getText());
            pst.setString(2,idade.getText());
            pst.setString(3,data.getText());
            pst.setString(4, sexo.getSelectedItem().toString());
            pst.setString(5,encarregado.getText());
            pst.setString(6,conctato.getText());
            pst.setString(7,endereco.getText());
                pst.setString(8,id.getText());
                    if ((id.getText().isEmpty()) || (nome1.getText().isEmpty())) {
                JOptionPane.showMessageDialog(null, "Campos obrigatorio vazio id ou nome");
            } else {
                int editar = pst.executeUpdate();
                if (editar > 0) {
                    JOptionPane.showMessageDialog(null, "Dados do aluno actualizado com sucesso");
    id.setText(null);
    nome1.setText(null);
    idade.setText(null);
   data.setText(null);
   sexo.setSelectedItem(null);
   encarregado.setText(null);
 conctato.setText(null);
    endereco.setText(null);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
}
    
    void excluir(){
    
    int confirma = JOptionPane.showConfirmDialog(null, "Apagar ?", "Antenção", JOptionPane.YES_NO_OPTION);
        if (confirma == JOptionPane.YES_OPTION) {
            String sql = "delete from estudantes where id=?";
            try {
                pst = conexao.prepareStatement(sql);
                pst.setString(1,   id.getText());
                int apagado = pst.executeUpdate();
                if (apagado > 0) {
                    JOptionPane.showMessageDialog(null, "Registo apagado");
            id.setText(null);
            nome1.setText(null);
            idade.setText(null);
           data.setText(null);
           sexo.setSelectedItem(null);
           encarregado.setText(null);
             conctato.setText(null);
            endereco.setText(null);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }

}
    
    
    private void consulta() {
        String sql = "select * from estudantes where Nome_do_aluno like ?";
        try {
            pst = conexao.prepareStatement(sql);
            //passando o conteudo da caixa de pesquisa  para o ?
            //atencao ao "%"  que e continuacao da string sql
            pst.setString(1, argumento.getText() + "%");
            rs = pst.executeQuery();
            //a linha abaixo usa a biblioteca rs2xml.jar para preenxer a tabela
           tabela.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
 

    void preencher_Tabela() {
        int setar = tabela.getSelectedRow();
       id.setText(tabela.getModel().getValueAt(setar, 0).toString());
       nome1.setText(tabela.getModel().getValueAt(setar, 1).toString());
      idade.setText(tabela.getModel().getValueAt(setar, 2).toString());
       data.setText(tabela.getModel().getValueAt(setar, 3).toString());
      sexo.setSelectedItem(tabela.getModel().getValueAt(setar, 4).toString());
   encarregado.setText(tabela.getModel().getValueAt(setar, 5).toString());
     conctato.setText(tabela.getModel().getValueAt(setar, 6).toString());
       endereco.setText(tabela.getModel().getValueAt(setar, 7).toString());
    }
    
    void cancelar(){
    id.setText("");
    nome1.setText("");
    idade.setText("");
    data.setText("");
    sexo.setSelectedItem("");
   encarregado.setText("");
  conctato.setText("");
   endereco.setText("");
    }
}