
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Conexao.Basededados;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * 
 */
public class Menu extends javax.swing.JFrame {

  Connection conexao = null;
    PreparedStatement PST = null;
    ResultSet Result = null;
            
    public Menu() {
        initComponents();
              conexao = Basededados.conector();
                datadecadastro.setDateFormatString("yyyy/MM/dd");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        nome = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        idade = new javax.swing.JTextField();
        BTsalvar = new javax.swing.JButton();
        BTcancelar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        sexo = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        encarregado = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        contacto = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        endereco = new javax.swing.JTextPane();
        jLabel11 = new javax.swing.JLabel();
        datadecadastro = new com.toedter.calendar.JDateChooser();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        jScrollPane2.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setMinimumSize(new java.awt.Dimension(600, 100));
        jPanel1.setLayout(null);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(61, 110, 30, 14);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nome do aluno");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(280, 100, 100, 14);

        id.setEnabled(false);
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        jPanel1.add(id);
        id.setBounds(150, 90, 66, 30);

        nome.setEnabled(false);
        nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeActionPerformed(evt);
            }
        });
        jPanel1.add(nome);
        nome.setBounds(370, 91, 220, 30);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Idade");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(50, 140, 50, 14);

        idade.setEnabled(false);
        idade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idadeActionPerformed(evt);
            }
        });
        jPanel1.add(idade);
        idade.setBounds(150, 130, 119, 30);

        BTsalvar.setText("Salvar");
        BTsalvar.setEnabled(false);
        BTsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTsalvarActionPerformed(evt);
            }
        });
        jPanel1.add(BTsalvar);
        BTsalvar.setBounds(179, 340, 63, 40);

        BTcancelar.setText("Cancelar");
        BTcancelar.setEnabled(false);
        BTcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTcancelarActionPerformed(evt);
            }
        });
        jPanel1.add(BTcancelar);
        BTcancelar.setBounds(252, 340, 80, 40);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Sexo");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(50, 180, 50, 14);

        sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));
        sexo.setEnabled(false);
        sexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sexoActionPerformed(evt);
            }
        });
        jPanel1.add(sexo);
        sexo.setBounds(150, 170, 110, 30);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Nome de encarregado");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(12, 225, 130, 14);

        encarregado.setEnabled(false);
        jPanel1.add(encarregado);
        encarregado.setBounds(150, 210, 150, 30);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Contacto");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(320, 220, 70, 14);

        contacto.setEnabled(false);
        contacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactoActionPerformed(evt);
            }
        });
        jPanel1.add(contacto);
        contacto.setBounds(380, 210, 120, 30);

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Endereço");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(50, 280, 60, 14);

        endereco.setEnabled(false);
        jScrollPane1.setViewportView(endereco);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(150, 260, 315, 53);

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Data de cadastro");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(290, 150, 110, 14);

        datadecadastro.setEnabled(false);
        jPanel1.add(datadecadastro);
        datadecadastro.setBounds(380, 140, 165, 30);

        jButton4.setText("Sair");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(480, 340, 51, 40);

        jButton5.setText("Novo");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(112, 340, 57, 40);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Preencha os dados do novo estudante");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(207, 49, 292, 22);

        jButton1.setText("Consultas");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(350, 340, 90, 40);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ESTUDANTES-NEGROS-REPRODUÇÃO-INTERNET.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        jLabel5.setRequestFocusEnabled(false);
        jPanel1.add(jLabel5);
        jLabel5.setBounds(4, 4, 590, 420);

        jTabbedPane1.addTab("Cadastro de alunos", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        novo();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void contactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactoActionPerformed

    private void sexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sexoActionPerformed

    private void BTcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTcancelarActionPerformed
        cancelar();

        // TODO add your handling code here:
    }//GEN-LAST:event_BTcancelarActionPerformed

    private void BTsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTsalvarActionPerformed

        adicionar();

        // TODO add your handling code here:
    }//GEN-LAST:event_BTsalvarActionPerformed

    private void nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeActionPerformed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

Consulta Consulta = new Consulta();
Consulta.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void idadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idadeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTcancelar;
    private javax.swing.JButton BTsalvar;
    private javax.swing.JTextField contacto;
    private com.toedter.calendar.JDateChooser datadecadastro;
    private javax.swing.JTextField encarregado;
    private javax.swing.JTextPane endereco;
    private javax.swing.JTextField id;
    private javax.swing.JTextField idade;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextField nome;
    private javax.swing.JComboBox<String> sexo;
    // End of variables declaration//GEN-END:variables

void novo(){
    id.setEnabled(true);
    nome.setEnabled(true);
    idade.setEnabled(true);
    datadecadastro.setEnabled(true);
    sexo.setEnabled(true);
   encarregado.setEnabled(true);
   contacto.setEnabled(true);
   endereco.setEnabled(true);
   BTsalvar.setEnabled(true);
   BTcancelar.setEnabled(true);
}
void cancelar (){
    id.setText("");
    nome.setText("");
    idade.setText("");
    datadecadastro.setDate(null);
    sexo.setSelectedItem("");
   encarregado.setText("");
   contacto.setText("");
   endereco.setText("");
   //alinha aseguir torna os valores dos em falso novamente
    id.setEnabled(false);
    nome.setEnabled(false);
    idade.setEnabled(false);
    datadecadastro.setEnabled(false);
    sexo.setEnabled(false);
   encarregado.setEnabled(false);
   contacto.setEnabled(false);
   endereco.setEnabled(false);
   BTsalvar.setEnabled(false);
   BTcancelar.setEnabled(false);
}
public void adicionar(){
 String sql = "insert into estudantes values (?,?,?,?,?,?,?,?);";
        
        try {
            PST = conexao.prepareStatement(sql);
          PST .setString(1,id.getText());
            PST .setString(2, nome.getText());
            PST.setString(3, idade.getText());
                    SimpleDateFormat Date_Format = new SimpleDateFormat("yyyy-MM-dd");
         String date = Date_Format.format(datadecadastro.getDate());
           PST.setString(4, date);
            PST .setString(5, sexo.getSelectedItem(). toString());
             PST .setString(6,encarregado.getText());
            PST .setString(7,contacto.getText());
             PST .setString(8,endereco.getText());
            
            //validacao dos campos obrigaorios
            if ((id.getText().isEmpty()) || (nome.getText().isEmpty()) ){
                JOptionPane.showMessageDialog(null, "Preencha todos os campos");
            } else {

                //a linha abaixo atualiza a tabela usuarios  com os dados do formulario
                //a estrutura abaixo e usada para confirmar a insercao dos dados na tabela
                int salvar = PST.executeUpdate();

                if (salvar > 0) {
                    JOptionPane.showMessageDialog(null, "Cadastros efectuado com sucesso");
                    //as linhas abaixos limpam os campos
  id.setText(null);
    nome.setText(null);
   idade.setText(null);
 datadecadastro.setDate(null);
   sexo.setSelectedItem(null);
   contacto.setText(null);
   encarregado.setText(null);
    contacto.setText(null);
    endereco.setText(null);
         
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }
        
}


